server:
  error:
    include-stacktrace: on_param
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: antonio
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG